# Generated by Django 5.1.2 on 2024-11-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_device_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesnapshot',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Unnamed Device', help_text='An optional name or title for this snapshot.', max_length=255),
            preserve_default=False,
        ),
    ]
