# Generated by Django 5.1.2 on 2024-11-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_devicesnapshot_name_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorvalues',
            name='weather_condition',
        ),
    ]
